2021-08-11 18:29:59,879 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting env: {'api_key': '20ef80315d2796a47ee939dd78c2077dbb6d82a1', 'notebook_name': 'Experiment1.ipynb'}
2021-08-11 18:29:59,879 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-11 18:29:59,879 INFO    MainThread:6313 [wandb_init.py:_log_setup():342] Logging user logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_182959-3tyj68sr/logs/debug.log
2021-08-11 18:29:59,880 INFO    MainThread:6313 [wandb_init.py:_log_setup():343] Logging internal logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_182959-3tyj68sr/logs/debug-internal.log
2021-08-11 18:29:59,880 INFO    MainThread:6313 [wandb_init.py:init():375] calling init triggers
2021-08-11 18:29:59,880 INFO    MainThread:6313 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-11 18:29:59,880 INFO    MainThread:6313 [wandb_init.py:init():397] re-initializing run, found existing run on stack: cumzb4uj
2021-08-11 18:29:59,881 INFO    MainThread:6313 [wandb_run.py:finish():1254] finishing run paul_shab/kaggle_nlp/cumzb4uj
2021-08-11 18:29:59,881 INFO    MainThread:6313 [jupyter.py:save_history():339] not saving jupyter history
2021-08-11 18:29:59,881 INFO    MainThread:6313 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-11 18:29:59,882 INFO    MainThread:6313 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-08-11 18:29:59,882 INFO    MainThread:6313 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-11 18:29:59,882 INFO    MainThread:6313 [wandb_run.py:_restore():1526] restore
2021-08-11 18:30:00,132 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-08-11 18:30:00,383 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-08-11 18:30:00,642 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 4467
}

2021-08-11 18:30:00,744 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 4467
}

2021-08-11 18:30:00,849 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 4467
}

2021-08-11 18:30:00,950 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,052 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,154 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,256 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,358 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,460 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,816 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,918 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:02,985 INFO    MainThread:6313 [wandb_run.py:_show_summary():1831] rendering summary
2021-08-11 18:30:02,987 INFO    MainThread:6313 [wandb_run.py:_show_history():1869] rendering history
2021-08-11 18:30:02,988 INFO    MainThread:6313 [wandb_run.py:_show_files():1898] logging synced files
2021-08-11 18:30:02,993 INFO    MainThread:6313 [wandb_init.py:init():424] starting backend
2021-08-11 18:30:02,993 INFO    MainThread:6313 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-11 18:30:02,995 INFO    MainThread:6313 [backend.py:ensure_launched():135] starting backend process...
2021-08-11 18:30:03,015 INFO    MainThread:6313 [backend.py:ensure_launched():140] started backend process with pid: 6989
2021-08-11 18:30:03,016 INFO    MainThread:6313 [wandb_init.py:init():429] backend started and connected
2021-08-11 18:30:03,029 INFO    MainThread:6313 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-11 18:30:03,031 INFO    MainThread:6313 [wandb_init.py:init():477] updated telemetry
2021-08-11 18:30:03,032 INFO    MainThread:6313 [wandb_init.py:init():500] communicating current version
2021-08-11 18:30:03,594 INFO    MainThread:6313 [wandb_init.py:init():505] got version response 
2021-08-11 18:30:03,594 INFO    MainThread:6313 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-11 18:30:03,798 INFO    MainThread:6313 [wandb_init.py:init():540] starting run threads in backend
2021-08-11 18:30:03,816 INFO    MainThread:6313 [wandb_run.py:_console_start():1584] atexit reg
2021-08-11 18:30:03,817 INFO    MainThread:6313 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-11 18:30:03,817 INFO    MainThread:6313 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-11 18:30:03,818 INFO    MainThread:6313 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-11 18:30:03,818 INFO    MainThread:6313 [wandb_init.py:init():565] run started, returning control to user process
2021-08-11 18:30:26,970 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting env: {'api_key': '20ef80315d2796a47ee939dd78c2077dbb6d82a1', 'notebook_name': 'Experiment1.ipynb'}
2021-08-11 18:30:26,970 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-11 18:30:26,970 INFO    MainThread:6313 [wandb_init.py:_log_setup():342] Logging user logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_183026-2w6n5s9l/logs/debug.log
2021-08-11 18:30:26,970 INFO    MainThread:6313 [wandb_init.py:_log_setup():343] Logging internal logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_183026-2w6n5s9l/logs/debug-internal.log
2021-08-11 18:30:26,971 INFO    MainThread:6313 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f328f56e590>
2021-08-11 18:30:26,971 INFO    MainThread:6313 [wandb_init.py:init():375] calling init triggers
2021-08-11 18:30:26,971 INFO    MainThread:6313 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-11 18:30:26,971 INFO    MainThread:6313 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 3tyj68sr
2021-08-11 18:30:26,972 INFO    MainThread:6313 [wandb_run.py:finish():1254] finishing run paul_shab/kaggle_nlp/3tyj68sr
