2021-08-11 18:07:55,451 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting env: {'api_key': '20ef80315d2796a47ee939dd78c2077dbb6d82a1', 'notebook_name': 'Experiment1.ipynb'}
2021-08-11 18:07:55,451 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-11 18:07:55,452 INFO    MainThread:6313 [wandb_init.py:_log_setup():342] Logging user logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_180755-1sjdiou4/logs/debug.log
2021-08-11 18:07:55,452 INFO    MainThread:6313 [wandb_init.py:_log_setup():343] Logging internal logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_180755-1sjdiou4/logs/debug-internal.log
2021-08-11 18:07:55,452 INFO    MainThread:6313 [wandb_init.py:init():375] calling init triggers
2021-08-11 18:07:55,452 INFO    MainThread:6313 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-11 18:07:55,452 INFO    MainThread:6313 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 4l56mnmo
2021-08-11 18:07:55,453 INFO    MainThread:6313 [wandb_run.py:finish():1254] finishing run paul_shab/kaggle_nlp/4l56mnmo
2021-08-11 18:07:55,453 INFO    MainThread:6313 [jupyter.py:save_history():339] not saving jupyter history
2021-08-11 18:07:55,453 INFO    MainThread:6313 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-11 18:07:55,453 INFO    MainThread:6313 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-08-11 18:07:55,453 INFO    MainThread:6313 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-11 18:07:55,454 INFO    MainThread:6313 [wandb_run.py:_restore():1526] restore
2021-08-11 18:07:55,880 ERROR   MainThread:6313 [wandb_init.py:init():801] error
Traceback (most recent call last):
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1562, in _atexit_cleanup
    self._on_finish()
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1698, in _on_finish
    self.history._flush()
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 886, in _history_callback
    row, step, publish_step=not_using_tensorboard
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 224, in publish_history
    self._publish_history(history)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 203, in _publish_history
    self._publish(rec)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 530, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 775, in init
    run = wi.init()
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 412, in init
    self._wl._global_run_stack[-1].finish()
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1258, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1571, in _atexit_cleanup
    self._backend.cleanup()
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 167, in cleanup
    self.interface.join()
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 830, in join
    _ = self._communicate(record)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2021-08-11 18:08:16,155 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting env: {'api_key': '20ef80315d2796a47ee939dd78c2077dbb6d82a1', 'notebook_name': 'Experiment1.ipynb'}
2021-08-11 18:08:16,155 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-11 18:08:16,155 INFO    MainThread:6313 [wandb_init.py:_log_setup():342] Logging user logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_180816-cumzb4uj/logs/debug.log
2021-08-11 18:08:16,155 INFO    MainThread:6313 [wandb_init.py:_log_setup():343] Logging internal logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_180816-cumzb4uj/logs/debug-internal.log
2021-08-11 18:08:16,156 INFO    MainThread:6313 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f328f7e12d0>
2021-08-11 18:08:16,156 INFO    MainThread:6313 [wandb_init.py:init():375] calling init triggers
2021-08-11 18:08:16,156 INFO    MainThread:6313 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-11 18:08:16,156 INFO    MainThread:6313 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 4l56mnmo
2021-08-11 18:08:16,157 INFO    MainThread:6313 [wandb_run.py:finish():1254] finishing run paul_shab/kaggle_nlp/4l56mnmo
2021-08-11 18:08:16,158 INFO    MainThread:6313 [wandb_init.py:init():424] starting backend
2021-08-11 18:08:16,158 INFO    MainThread:6313 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-11 18:08:16,161 INFO    MainThread:6313 [backend.py:ensure_launched():135] starting backend process...
2021-08-11 18:08:16,179 INFO    MainThread:6313 [backend.py:ensure_launched():140] started backend process with pid: 6750
2021-08-11 18:08:16,180 INFO    MainThread:6313 [wandb_init.py:init():429] backend started and connected
2021-08-11 18:08:16,194 INFO    MainThread:6313 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-11 18:08:16,196 INFO    MainThread:6313 [wandb_init.py:init():477] updated telemetry
2021-08-11 18:08:16,197 INFO    MainThread:6313 [wandb_init.py:init():500] communicating current version
2021-08-11 18:08:16,765 INFO    MainThread:6313 [wandb_init.py:init():505] got version response 
2021-08-11 18:08:16,765 INFO    MainThread:6313 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-11 18:08:16,972 INFO    MainThread:6313 [wandb_init.py:init():540] starting run threads in backend
2021-08-11 18:08:16,989 INFO    MainThread:6313 [wandb_run.py:_console_start():1584] atexit reg
2021-08-11 18:08:16,990 INFO    MainThread:6313 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-11 18:08:16,990 INFO    MainThread:6313 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-11 18:08:16,991 INFO    MainThread:6313 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-11 18:08:16,991 INFO    MainThread:6313 [wandb_init.py:init():565] run started, returning control to user process
2021-08-11 18:09:27,928 INFO    MainThread:6313 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-11 18:09:27,928 INFO    MainThread:6313 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-11 18:28:09,958 INFO    MainThread:6313 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-11 18:28:12,755 INFO    MainThread:6313 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-11 18:28:12,755 INFO    MainThread:6313 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-11 18:29:55,599 INFO    MainThread:6313 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-11 18:29:55,601 INFO    MainThread:6313 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-11 18:29:55,601 INFO    MainThread:6313 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-11 18:29:59,539 INFO    MainThread:6313 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-11 18:29:59,879 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting env: {'api_key': '20ef80315d2796a47ee939dd78c2077dbb6d82a1', 'notebook_name': 'Experiment1.ipynb'}
2021-08-11 18:29:59,879 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-11 18:29:59,879 INFO    MainThread:6313 [wandb_init.py:_log_setup():342] Logging user logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_182959-3tyj68sr/logs/debug.log
2021-08-11 18:29:59,880 INFO    MainThread:6313 [wandb_init.py:_log_setup():343] Logging internal logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_182959-3tyj68sr/logs/debug-internal.log
2021-08-11 18:29:59,880 INFO    MainThread:6313 [wandb_init.py:init():375] calling init triggers
2021-08-11 18:29:59,880 INFO    MainThread:6313 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-11 18:29:59,880 INFO    MainThread:6313 [wandb_init.py:init():397] re-initializing run, found existing run on stack: cumzb4uj
2021-08-11 18:29:59,881 INFO    MainThread:6313 [wandb_run.py:finish():1254] finishing run paul_shab/kaggle_nlp/cumzb4uj
2021-08-11 18:29:59,881 INFO    MainThread:6313 [jupyter.py:save_history():339] not saving jupyter history
2021-08-11 18:29:59,881 INFO    MainThread:6313 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-11 18:29:59,882 INFO    MainThread:6313 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-08-11 18:29:59,882 INFO    MainThread:6313 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-11 18:29:59,882 INFO    MainThread:6313 [wandb_run.py:_restore():1526] restore
2021-08-11 18:30:00,132 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-08-11 18:30:00,383 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-08-11 18:30:00,642 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 4467
}

2021-08-11 18:30:00,744 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 4467
}

2021-08-11 18:30:00,849 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 4467
}

2021-08-11 18:30:00,950 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,052 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,154 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,256 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,358 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,460 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,816 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:01,918 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4467
  total_bytes: 4467
}

2021-08-11 18:30:02,985 INFO    MainThread:6313 [wandb_run.py:_show_summary():1831] rendering summary
2021-08-11 18:30:02,987 INFO    MainThread:6313 [wandb_run.py:_show_history():1869] rendering history
2021-08-11 18:30:02,988 INFO    MainThread:6313 [wandb_run.py:_show_files():1898] logging synced files
2021-08-11 18:30:02,993 INFO    MainThread:6313 [wandb_init.py:init():424] starting backend
2021-08-11 18:30:02,993 INFO    MainThread:6313 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-11 18:30:02,995 INFO    MainThread:6313 [backend.py:ensure_launched():135] starting backend process...
2021-08-11 18:30:03,015 INFO    MainThread:6313 [backend.py:ensure_launched():140] started backend process with pid: 6989
2021-08-11 18:30:03,016 INFO    MainThread:6313 [wandb_init.py:init():429] backend started and connected
2021-08-11 18:30:03,029 INFO    MainThread:6313 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-11 18:30:03,031 INFO    MainThread:6313 [wandb_init.py:init():477] updated telemetry
2021-08-11 18:30:03,032 INFO    MainThread:6313 [wandb_init.py:init():500] communicating current version
2021-08-11 18:30:03,594 INFO    MainThread:6313 [wandb_init.py:init():505] got version response 
2021-08-11 18:30:03,594 INFO    MainThread:6313 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-11 18:30:03,798 INFO    MainThread:6313 [wandb_init.py:init():540] starting run threads in backend
2021-08-11 18:30:03,816 INFO    MainThread:6313 [wandb_run.py:_console_start():1584] atexit reg
2021-08-11 18:30:03,817 INFO    MainThread:6313 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-11 18:30:03,817 INFO    MainThread:6313 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-11 18:30:03,818 INFO    MainThread:6313 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-11 18:30:03,818 INFO    MainThread:6313 [wandb_init.py:init():565] run started, returning control to user process
2021-08-11 18:30:26,970 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting env: {'api_key': '20ef80315d2796a47ee939dd78c2077dbb6d82a1', 'notebook_name': 'Experiment1.ipynb'}
2021-08-11 18:30:26,970 INFO    MainThread:6313 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-11 18:30:26,970 INFO    MainThread:6313 [wandb_init.py:_log_setup():342] Logging user logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_183026-2w6n5s9l/logs/debug.log
2021-08-11 18:30:26,970 INFO    MainThread:6313 [wandb_init.py:_log_setup():343] Logging internal logs to /home/iris/paulshab/KaggleComp/wandb/run-20210811_183026-2w6n5s9l/logs/debug-internal.log
2021-08-11 18:30:26,971 INFO    MainThread:6313 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f328f56e590>
2021-08-11 18:30:26,971 INFO    MainThread:6313 [wandb_init.py:init():375] calling init triggers
2021-08-11 18:30:26,971 INFO    MainThread:6313 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-11 18:30:26,971 INFO    MainThread:6313 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 3tyj68sr
2021-08-11 18:30:26,972 INFO    MainThread:6313 [wandb_run.py:finish():1254] finishing run paul_shab/kaggle_nlp/3tyj68sr
2021-08-11 18:30:26,972 INFO    MainThread:6313 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-11 18:30:26,973 INFO    MainThread:6313 [wandb_run.py:_restore():1526] restore
2021-08-11 18:30:27,356 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-08-11 18:30:27,611 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-08-11 18:30:27,818 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 3489
}

2021-08-11 18:30:27,921 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 3775
}

2021-08-11 18:30:28,023 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 3775
}

2021-08-11 18:30:28,124 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3775
  total_bytes: 3775
}

2021-08-11 18:30:28,228 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3775
  total_bytes: 3775
}

2021-08-11 18:30:28,330 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3775
  total_bytes: 3775
}

2021-08-11 18:30:28,432 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3775
  total_bytes: 3775
}

2021-08-11 18:30:28,534 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3775
  total_bytes: 3775
}

2021-08-11 18:30:29,472 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3775
  total_bytes: 3775
}

2021-08-11 18:30:29,575 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3775
  total_bytes: 3775
}

2021-08-11 18:30:30,643 INFO    MainThread:6313 [wandb_run.py:_show_summary():1831] rendering summary
2021-08-11 18:30:30,644 INFO    MainThread:6313 [wandb_run.py:_show_history():1869] rendering history
2021-08-11 18:30:30,646 INFO    MainThread:6313 [wandb_run.py:_show_files():1898] logging synced files
2021-08-11 18:30:30,650 INFO    MainThread:6313 [wandb_init.py:init():424] starting backend
2021-08-11 18:30:30,651 INFO    MainThread:6313 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-11 18:30:30,654 INFO    MainThread:6313 [backend.py:ensure_launched():135] starting backend process...
2021-08-11 18:30:30,674 INFO    MainThread:6313 [backend.py:ensure_launched():140] started backend process with pid: 7031
2021-08-11 18:30:30,675 INFO    MainThread:6313 [wandb_init.py:init():429] backend started and connected
2021-08-11 18:30:30,690 INFO    MainThread:6313 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-11 18:30:30,692 INFO    MainThread:6313 [wandb_init.py:init():477] updated telemetry
2021-08-11 18:30:30,693 INFO    MainThread:6313 [wandb_init.py:init():500] communicating current version
2021-08-11 18:30:31,245 INFO    MainThread:6313 [wandb_init.py:init():505] got version response 
2021-08-11 18:30:31,245 INFO    MainThread:6313 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-11 18:30:31,450 INFO    MainThread:6313 [wandb_init.py:init():540] starting run threads in backend
2021-08-11 18:30:31,467 INFO    MainThread:6313 [wandb_run.py:_console_start():1584] atexit reg
2021-08-11 18:30:31,468 INFO    MainThread:6313 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-11 18:30:31,468 INFO    MainThread:6313 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-11 18:30:31,468 INFO    MainThread:6313 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-11 18:30:31,468 INFO    MainThread:6313 [wandb_init.py:init():565] run started, returning control to user process
2021-08-11 18:30:38,048 INFO    MainThread:6313 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-11 18:30:38,048 INFO    MainThread:6313 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-12 20:30:59,645 INFO    MainThread:6313 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-12 20:30:59,646 INFO    MainThread:6313 [wandb_run.py:_restore():1526] restore
2021-08-12 20:31:00,200 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-08-12 20:31:00,401 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-08-12 20:31:00,543 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 9916
}

2021-08-12 20:31:00,646 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 9916
}

2021-08-12 20:31:00,748 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 9916
}

2021-08-12 20:31:00,849 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9916
  total_bytes: 9916
}

2021-08-12 20:31:00,951 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9916
  total_bytes: 9916
}

2021-08-12 20:31:01,053 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9916
  total_bytes: 9916
}

2021-08-12 20:31:01,154 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9916
  total_bytes: 9916
}

2021-08-12 20:31:01,257 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9916
  total_bytes: 9916
}

2021-08-12 20:31:01,617 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9916
  total_bytes: 9916
}

2021-08-12 20:31:01,719 INFO    MainThread:6313 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9916
  total_bytes: 9916
}

