2021-08-14 14:33:28,427 INFO    MainThread:3879 [wandb_setup.py:_flush():69] setting env: {'api_key': '20ef80315d2796a47ee939dd78c2077dbb6d82a1', 'notebook_name': 'Experiment1.ipynb'}
2021-08-14 14:33:28,427 INFO    MainThread:3879 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-14 14:33:28,427 INFO    MainThread:3879 [wandb_init.py:_log_setup():342] Logging user logs to /home/iris/paulshab/KaggleComp/wandb/run-20210814_143328-36wun2rz/logs/debug.log
2021-08-14 14:33:28,427 INFO    MainThread:3879 [wandb_init.py:_log_setup():343] Logging internal logs to /home/iris/paulshab/KaggleComp/wandb/run-20210814_143328-36wun2rz/logs/debug-internal.log
2021-08-14 14:33:28,428 INFO    MainThread:3879 [wandb_init.py:init():375] calling init triggers
2021-08-14 14:33:28,428 INFO    MainThread:3879 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-14 14:33:28,428 INFO    MainThread:3879 [wandb_init.py:init():397] re-initializing run, found existing run on stack: coqax9ge
2021-08-14 14:33:28,429 INFO    MainThread:3879 [wandb_run.py:finish():1254] finishing run paul_shab/kaggle_nlp/coqax9ge
2021-08-14 14:33:28,448 INFO    MainThread:3879 [jupyter.py:save_history():339] not saving jupyter history
2021-08-14 14:33:28,448 INFO    MainThread:3879 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-14 14:33:28,448 INFO    MainThread:3879 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-08-14 14:33:28,448 INFO    MainThread:3879 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-14 14:33:28,448 INFO    MainThread:3879 [wandb_run.py:_restore():1526] restore
2021-08-14 14:33:28,968 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-08-14 14:33:29,255 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 618
}

2021-08-14 14:33:29,373 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 8349
}

2021-08-14 14:33:29,476 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 618
  total_bytes: 8349
}

2021-08-14 14:33:29,577 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6019
  total_bytes: 8349
}

2021-08-14 14:33:29,680 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8349
  total_bytes: 8349
}

2021-08-14 14:33:29,782 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8349
  total_bytes: 8349
}

2021-08-14 14:33:29,884 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8349
  total_bytes: 8349
}

2021-08-14 14:33:29,986 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8349
  total_bytes: 8349
}

2021-08-14 14:33:30,089 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8349
  total_bytes: 8349
}

2021-08-14 14:33:30,455 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8349
  total_bytes: 8349
}

2021-08-14 14:33:30,557 INFO    MainThread:3879 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8349
  total_bytes: 8349
}

2021-08-14 14:33:31,624 INFO    MainThread:3879 [wandb_run.py:_show_files():1898] logging synced files
2021-08-14 14:33:31,630 INFO    MainThread:3879 [wandb_init.py:init():424] starting backend
2021-08-14 14:33:31,630 INFO    MainThread:3879 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-14 14:33:31,633 INFO    MainThread:3879 [backend.py:ensure_launched():135] starting backend process...
2021-08-14 14:33:31,652 INFO    MainThread:3879 [backend.py:ensure_launched():140] started backend process with pid: 4022
2021-08-14 14:33:31,653 INFO    MainThread:3879 [wandb_init.py:init():429] backend started and connected
2021-08-14 14:33:31,666 INFO    MainThread:3879 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-14 14:33:31,668 INFO    MainThread:3879 [wandb_init.py:init():477] updated telemetry
2021-08-14 14:33:31,668 INFO    MainThread:3879 [wandb_init.py:init():500] communicating current version
2021-08-14 14:33:32,251 INFO    MainThread:3879 [wandb_init.py:init():505] got version response 
2021-08-14 14:33:32,251 INFO    MainThread:3879 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-14 14:33:32,454 INFO    MainThread:3879 [wandb_init.py:init():540] starting run threads in backend
2021-08-14 14:33:32,472 INFO    MainThread:3879 [wandb_run.py:_console_start():1584] atexit reg
2021-08-14 14:33:32,473 INFO    MainThread:3879 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-14 14:33:32,473 INFO    MainThread:3879 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-14 14:33:32,474 INFO    MainThread:3879 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-14 14:33:32,474 INFO    MainThread:3879 [wandb_init.py:init():565] run started, returning control to user process
2021-08-14 16:17:31,291 INFO    MainThread:3879 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-14 16:17:31,292 INFO    MainThread:3879 [wandb_run.py:_restore():1526] restore
